### ISSUE TITLE
Aufteilen in mehrere Dateien

### ISSUE THREAD

**Issue by memo42** [beac0n/Latex_Vorlage#1]
Finde die Ergebnisse, die die Vorlage liefert sehr schön, denke aber der Code könnte noch schöner sein, was vor allem durch das sinnvolle Aufspalten in mehrere Dateien und mehr Kommentare erreicht werden könnte.

**Comment by beac0n** [comment]
Hallo memo, 
dann mach das doch und stell ein pull-request :)
https://help.github.com/articles/using-pull-requests/

**Comment by memo42** [comment]
hab ich vor... wollte nur mal feststellen ob du damit einverstanden bist bevor ich mir die Arbeit mache.

**Comment by beac0n** [comment]
aufteilen in mehrere Dateien schafft Übersicht - von daher ne super sache...
Ich würde eventuell noch nen Schritt weiter gehen und das Latex durch nen Ordner loopen lassen der Dateien nach dem Format "1_Kapitel1Beschreibung" "1_1_Kapitel1.1Beschreibung" etc. einliest.
So ähnlich wie Jekyll also :>

**Comment by beac0n** [comment]
Anyway. der Issue ist ja jetzt erledigt - also mach ich ihn zu :)
