### ISSUE TITLE
Globale Variablen

### ISSUE THREAD

**Issue by beac0n** [beac0n/Latex_Vorlage#3]
Globale Variablen setzen wie z.B.:
Schreiber der Arbeit
Name der Arbeit
Name der Hochschule
Name der Fakultät
Abgabedatum

...

**Comment by memo42** [comment]
hast du doch eigentlich in 920a9e5ca258dbde7f92284c146601bdac9a296c (auch wenn der etwas komisch benannt ist) gemacht, oder?

**Comment by beac0n** [comment]
ja hab ich da gemacht - daher kann man den hier eig. schließen ^^,
Ich muss mich mal an die git message convention halten :>
